Buttons and api
SummerPractice2022/CatsGallery pull request #2
Opened 2022-07-09 15:00 UTC by DeM0NChiCk

2022-07-09 16:30 UTC, AvanNorth requested changes
В целом норм но есть ряд придирок как с форматированием так и просто с кодом

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/activities/MainActivity.kt
> +    private var _binding: ActivityMainBinding? = null
не забываем, что есть такая штука как lateinit

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/activities/MainActivity.kt
> +    private var _binding: ActivityMainBinding? = null
и разве нельзя сразу просто  binding = ActivityMainBinding.inflate(layoutInflater), я что то не помню чтобы нужно было заморачиваться подобным образом

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/activities/MainActivity.kt
> +        val bottomView =findViewById<BottomNavigationView>(R.id.bottomNavigationView)
после = не хватает пробела) Вообще советую завести привычку либо после написания кода прожимать ctrl alt L, либо, если пушите с идеи, можно подключить автоформатирование кода

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/activities/MainActivity.kt
> +
Старайтесь не делать подобные пропасти в коде (два переноса строки), если это оправдано по смыслу то можно, а так выглядит неоч

2022-07-09 16:30 UTC, AvanNorth commented on .idea/deploymentTargetDropDown.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Лишний файл, не забывайте в гитигнор подобные добавлять

2022-07-09 16:30 UTC, AvanNorth commented on .idea/misc.xml
>        <map>
тоже самое)

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/fragments/FavoritesFragment.kt
> +    private var adapter: ImageFavAdapter? = null
опять таки напоминаю про lateinit

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/fragments/ImageFragment.kt
похоже на пустую строку перед закрывающей скобкой, выше уже писал поп поводу форматирования

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/fragments/MainFragment.kt
> +
тут вообще огромная расщелина)

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/fragments/MainFragment.kt
> +            binding.recyclerViewMain.adapter=adapter
опять пробелы пропали)

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/fragments/recycler/breed/BreedAdapter.kt
> +
опять какие то пустоты

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/java/ru/teamfive/catsgallery/ui/fragments/recycler/breed/BreedHolder.kt
> +
я так погляжу кого то такой кодстайл да?)

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:layout_width="292dp"
а почему размеры какие то слишком конкретные? И зачем itemCount = 67 (я прост рил не помню что конкретно этот параметр делает)

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/res/layout/fragment_image.xml
> +        android:id="@+id/button9"
удобно с такими id?))

2022-07-09 16:30 UTC, AvanNorth commented on app/src/main/res/layout/item_favorites.xml
> +        android:layout_width="wrap_content"
вроде бы так картинка может скакать по размерам, как раз изображения я обычно фиксирую по размеру, либо чтобы были не больше какого то размера

2022-07-09 19:47 UTC, DeM0NChiCk commented on app/src/main/java/ru/teamfive/catsgallery/ui/activities/MainActivity.kt
> +    private var _binding: ActivityMainBinding? = null
нельзя, я попробовал, при запуске приложение не запускается ( я не помню уже почему, нам это Наиль Камилевич показал)

2022-07-10 12:47 UTC, AvanNorth approved these changes

2022-07-10 12:47 UTC, merged